package io.github.timoptr.mdiicons

/**
 * Historical MDI renames not covered by the catalog aliases, so icon names persisted by
 * older app versions keep resolving. Curated from the tables the frontend ships during MDI
 * major version migrations, accumulated in
 * https://github.com/home-assistant/iOS/blob/main/Sources/HAIconic/Sources/MDIMigration.swift
 */
internal val mdiRenamedNames: Map<String, String> =
    mapOf(
        "account-badge-alert" to "badge-account-alert",
        "account-badge-alert-outline" to "badge-account-alert-outline",
        "account-badge-horizontal" to "badge-account-horizontal",
        "account-badge-horizontal-outline" to "badge-account-horizontal-outline",
        "account-card-details" to "card-account-details",
        "account-card-details-outline" to "card-account-details-outline",
        "audiobook" to "book-music",
        "azure" to "microsoft-azure",
        "azure-devops" to "microsoft-azure-devops",
        "bolnisi-cross" to "cross-bolnisi",
        "boom-gate-down" to "boom-gate-arrow-down",
        "boom-gate-down-outline" to "boom-gate-arrow-down-outline",
        "camcorder-box" to "video-box",
        "camcorder-box-off" to "video-box-off",
        "cellphone-android" to "cellphone",
        "cellphone-iphone" to "cellphone",
        "cellphone-settings-variant" to "cellphone-cog",
        "celtic-cross" to "cross-celtic",
        "cowboy" to "account-cowboy-hat",
        "do-not-disturb" to "minus-circle",
        "edge" to "microsoft-edge",
        "face-profile-woman" to "face-woman-profile",
        "face-shimmer" to "face-man-shimmer",
        "face-shimmer-outline" to "face-man-shimmer-outline",
        "file-pdf" to "file-pdf-box",
        "file-pdf-box-outline" to "file-pdf-box",
        "file-pdf-outline" to "file-pdf-box",
        "file-settings-variant" to "file-cog",
        "file-settings-variant-outline" to "file-cog-outline",
        "floor-lamp-variant" to "floor-lamp-torchiere-variant",
        "folder-settings-variant" to "folder-cog",
        "folder-settings-variant-outline" to "folder-cog-outline",
        "gif" to "file-gif-box",
        "github-circle" to "github",
        "gradient" to "gradient-vertical",
        "hand-left" to "hand-back-left",
        "hand-right" to "hand-back-right",
        "internet-explorer" to "microsoft-internet-explorer",
        "json" to "code-json",
        "kotlin" to "language-kotlin",
        "laptop-chromebook" to "laptop",
        "laptop-mac" to "laptop",
        "laptop-windows" to "laptop",
        "library-books" to "filmstrip-box",
        "library-video" to "play-box-multiple",
        "markdown" to "language-markdown",
        "markdown-outline" to "language-markdown-outline",
        "message-settings-variant" to "message-cog",
        "message-settings-variant-outline" to "message-cog-outline",
        "microsoft-dynamics" to "microsoft-dynamics-365",
        "network-router" to "router-network",
        "office" to "microsoft-office",
        "onedrive" to "microsoft-onedrive",
        "onenote" to "microsoft-onenote",
        "outlook" to "microsoft-outlook",
        "pdf-box" to "file-pdf-box",
        "periodic-table-co" to "molecule-co",
        "periodic-table-co2" to "molecule-co2",
        "pharmacy" to "mortar-pestle-plus",
        "playstation" to "sony-playstation",
        "ruby" to "language-ruby",
        "selection-mutliple" to "selection-multiple",
        "sort-alphabetical" to "sort-alphabetical-variant",
        "sort-numeric" to "sort-numeric-variant",
        "syllabary-katakana-half-width" to "syllabary-katakana-halfwidth",
        "tablet-ipad" to "tablet",
        "teach" to "human-male-board",
        "textarea" to "form-textarea",
        "textbox" to "form-textbox",
        "textbox-lock" to "form-textbox-lock",
        "textbox-password" to "form-textbox-password",
        "towing" to "tow-truck",
        "visual-studio" to "microsoft-visual-studio",
        "visual-studio-code" to "microsoft-visual-studio-code",
        "voice" to "account-voice",
        "voice-off" to "account-voice-off",
        "wall-sconce-variant" to "wall-sconce-round-variant",
        "wii" to "nintendo-wii",
        "wiiu" to "nintendo-wiiu",
        "windows" to "microsoft-windows",
        "windows-classic" to "microsoft-windows-classic",
        "xbox" to "microsoft-xbox",
        "xbox-controller" to "microsoft-xbox-controller",
        "xbox-controller-battery-alert" to "microsoft-xbox-controller-battery-alert",
        "xbox-controller-battery-charging" to "microsoft-xbox-controller-battery-charging",
        "xbox-controller-battery-empty" to "microsoft-xbox-controller-battery-empty",
        "xbox-controller-battery-full" to "microsoft-xbox-controller-battery-full",
        "xbox-controller-battery-low" to "microsoft-xbox-controller-battery-low",
        "xbox-controller-battery-medium" to "microsoft-xbox-controller-battery-medium",
        "xbox-controller-battery-unknown" to "microsoft-xbox-controller-battery-unknown",
        "xbox-controller-menu" to "microsoft-xbox-controller-menu",
        "xbox-controller-off" to "microsoft-xbox-controller-off",
        "xbox-controller-view" to "microsoft-xbox-controller-view",
    )
