import java.io.File
import org.gradle.api.GradleException

internal const val GENERATED_PACKAGE = "io.github.timoptr.mdiicons.generated"

/** Number of icons per generated file, keeping each map initializer well under the JVM method size limit. */
internal const val CHUNK_SIZE = 500

/** An icon from `meta.json` joined with its SVG path data, [aliases] are alternative names. */
internal data class MdiMetaIcon(val name: String, val pathData: String, val aliases: List<String>)

/**
 * Pure generation logic behind [UpdateMdiIconsTask] and [VerifyMdiIconsTask], separated from the
 * Gradle machinery so it can be unit tested.
 *
 * The code is emitted with plain Kotlin string templates on purpose. The output has almost no
 * static text; it is logic producing thousands of near-identical lines, so a templating engine
 * would only relocate the interesting work into an untyped template while Kotlin escaping would
 * stay hand-rolled either way. KotlinPoet would handle escaping and keywords, but the real risks
 * here are semantic (naming policy, alias resolution, chunking), which it cannot see, and its
 * formatter co-owns the output bytes, so a KotlinPoet upgrade could reformat the whole catalog
 * into a catalog-wide diff with no semantic change. Revisit if the generated code ever grows
 * structurally richer than vals and literal collections.
 */
internal object MdiCatalogGenerator {

    private val svgPathRegex = """ d="([^"]+)"""".toRegex()
    private val generatedVersionRegex = """MDI_VERSION: String = "([^"]+)"""".toRegex()

    /** Extracts the single path data of an MDI svg file, or null when the file holds none. */
    fun extractPathData(svg: String): String? = svgPathRegex.find(svg)?.groupValues?.get(1)

    /**
     * Joins the parsed `meta.json` entries with the path data extracted per icon name, sorted by
     * icon name so the generated output is deterministic regardless of `meta.json` order.
     */
    fun buildIcons(metaEntries: List<Map<*, *>>, svgPathByName: Map<String, String>): List<MdiMetaIcon> =
        metaEntries.map { entry ->
            val name = entry["name"] as String
            MdiMetaIcon(
                name = name,
                pathData = svgPathByName[name]
                    ?: throw GradleException("meta.json entry $name has no matching svg/$name.svg"),
                aliases = (entry["aliases"] as? List<*>).orEmpty().map { alias -> alias as String },
            )
        }.sortedBy(MdiMetaIcon::name)

    /** Reads the version recorded in a generated MdiMeta.kt, or null when absent. */
    fun readGeneratedVersion(metaFile: File): String? = metaFile.takeIf(File::exists)?.readText()
        ?.let { generatedVersionRegex.find(it) }
        ?.groupValues?.get(1)

    /**
     * Writes the generated catalog for [icons] into [outputDir], replacing any previous output.
     *
     * [icons] must be sorted by name (as [buildIcons] returns them): the generated routing table
     * of chunk first names locates an icon's chunk by name order, so an unsorted catalog would
     * generate fine but silently break lookups. Unsorted input fails here instead.
     */
    fun generate(version: String, icons: List<MdiMetaIcon>, outputDir: File) {
        icons.zipWithNext().firstOrNull { (previous, next) -> previous.name > next.name }
            ?.let { (previous, next) ->
                throw GradleException("Icons must be sorted by name, but ${previous.name} precedes ${next.name}")
            }

        outputDir.cleanGeneratedSources()

        val plainHeader = """
            // Generated by :shared:updateMdiIcons from @mdi/svg $version. Do not edit manually.
            package $GENERATED_PACKAGE
        """.trimIndent()
        val header = plainHeader +
            "\n\nimport io.github.timoptr.mdiicons.Mdi" +
            "\nimport io.github.timoptr.mdiicons.MdiIcon"

        val valNameByIcon = buildValNames(icons)
        val chunks = icons.chunked(CHUNK_SIZE)
        chunks.forEachIndexed { index, chunk ->
            outputDir.writeIconChunk(index, chunk, valNameByIcon, header)
        }

        val aliasChunks = buildAliases(icons).entries.chunked(CHUNK_SIZE)
        aliasChunks.forEachIndexed { index, chunk ->
            outputDir.writeAliasChunk(index, chunk, plainHeader)
        }

        outputDir.writeMeta(version, chunks, plainHeader)
        outputDir.writeAliasIndex(aliasChunks, plainHeader)
    }

    private fun File.cleanGeneratedSources() {
        deleteRecursively()
        mkdirs()
    }

    /**
     * Maps every icon name to the name of its backing val, failing on icons whose accessors
     * collide case insensitively, which would clash on case-insensitive tooling.
     */
    private fun buildValNames(icons: List<MdiMetaIcon>): Map<String, String> {
        val collisions = mutableMapOf<String, String>()
        return icons.associate { icon ->
            val accessor = icon.name.toPascalCaseIdentifier()
            collisions.put(accessor.lowercase(), icon.name)?.let { previous ->
                throw GradleException("Icons $previous and ${icon.name} both map to the accessor $accessor")
            }
            icon.name to accessor.toBackingValName()
        }
    }

    /**
     * Resolves aliases: canonical names win over aliases, the first icon claiming an alias keeps
     * it ("first" meaning alphabetical, since [icons] is sorted by name). The result is sorted by
     * alias so the generated files are deterministic.
     */
    private fun buildAliases(icons: List<MdiMetaIcon>): Map<String, String> {
        val iconNames = icons.mapTo(mutableSetOf(), MdiMetaIcon::name)
        return buildMap {
            icons.forEach { icon ->
                icon.aliases.forEach { alias ->
                    if (alias !in iconNames) putIfAbsent(alias, icon.name)
                }
            }
        }.toSortedMap()
    }

    // One val and one accessor per icon, grouped in chunked files: the vals keep dex cost low
    // (a handful of classes) while static references stay compile-time safe with no string
    // indirection.
    private fun File.writeIconChunk(
        index: Int,
        chunk: List<MdiMetaIcon>,
        valNameByIcon: Map<String, String>,
        header: String,
    ) {
        File(this, "MdiIcons$index.kt").writeText(
            buildString {
                appendLine(header)
                appendLine()
                chunk.forEach { icon ->
                    val valName = valNameByIcon.getValue(icon.name)
                    appendLine("internal val $valName = MdiIcon(\"${icon.name}\", \"${icon.pathData.escaped()}\")")
                    appendLine()
                    appendLine("/** The MDI \"${icon.name}\" icon. */")
                    appendLine("val Mdi.${icon.name.toPascalCaseIdentifier()}: MdiIcon get() = $valName")
                    appendLine()
                }
                appendLine("internal val mdiIcons$index: List<MdiIcon> = listOf(")
                chunk.forEach { icon ->
                    appendLine("    ${valNameByIcon.getValue(icon.name)},")
                }
                appendLine(")")
            },
        )
    }

    // Aliases resolve to names rather than icon vals on purpose: referencing a val would
    // initialize the icon's whole chunk, defeating the chunk routing of [lookup].
    private fun File.writeAliasChunk(index: Int, chunk: List<Map.Entry<String, String>>, plainHeader: String) {
        File(this, "MdiAliases$index.kt").writeText(
            buildString {
                appendLine(plainHeader)
                appendLine()
                appendLine("internal val mdiAliases$index: Map<String, String> = mapOf(")
                chunk.forEach { (alias, name) ->
                    appendLine("    \"$alias\" to \"$name\",")
                }
                appendLine(")")
            },
        )
    }

    private fun File.writeMeta(version: String, chunks: List<List<MdiMetaIcon>>, plainHeader: String) {
        File(this, "MdiMeta.kt").writeText(
            buildString {
                appendLine(plainHeader)
                appendLine()
                appendLine("import io.github.timoptr.mdiicons.MdiIcon")
                appendLine()
                appendLine("/** Version of the @mdi/svg package the catalog was generated from. */")
                appendLine("internal const val MDI_VERSION: String = \"$version\"")
                appendLine()
                appendLine("/** Number of icon chunks addressable through [mdiIconChunk]. */")
                appendLine("internal const val MDI_CHUNK_COUNT: Int = ${chunks.size}")
                appendLine()
                appendLine("/** First icon name of each sorted chunk, to route a lookup to a single chunk. */")
                appendLine("internal val mdiChunkFirstNames: List<String> = listOf(")
                chunks.forEach { appendLine("    \"${it.first().name}\",") }
                appendLine(")")
                appendLine()
                appendLine("/** Returns one sorted chunk of the catalog, loading only that chunk's icons. */")
                appendLine("internal fun mdiIconChunk(index: Int): List<MdiIcon> = when (index) {")
                chunks.indices.forEach { appendLine("    $it -> mdiIcons$it") }
                appendLine("    else -> error(\"Unknown MDI chunk \$index\")")
                appendLine("}")
            },
        )
    }

    // In its own file so the alias table only loads when a lookup misses the canonical names.
    private fun File.writeAliasIndex(aliasChunks: List<List<Map.Entry<String, String>>>, plainHeader: String) {
        File(this, "MdiAliasesIndex.kt").writeText(
            buildString {
                appendLine(plainHeader)
                appendLine()
                appendLine("/** Alternative icon names to the canonical name holding the icon. */")
                appendLine(
                    "internal val mdiAliases: Map<String, String> = buildMap(${aliasChunks.sumOf {
                        it.size
                    }}) {",
                )
                aliasChunks.indices.forEach { appendLine("    putAll(mdiAliases$it)") }
                appendLine("}")
            },
        )
    }

    private fun String.escaped(): String = replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\${'$'}")
}

/** Converts an MDI icon name to a Kotlin identifier, for instance "account-alert" to "AccountAlert". */
internal fun String.toPascalCaseIdentifier(): String {
    val identifier = split('-').joinToString("") { part ->
        part.replaceFirstChar(Char::uppercaseChar)
    }
    return if (identifier.first().isDigit()) "_$identifier" else identifier
}

/**
 * Derives the backing val name of an accessor, distinct from it even when it starts with an
 * underscore, and never a Kotlin keyword (the icon named "package" exists).
 */
internal fun String.toBackingValName(): String {
    val camel = replaceFirstChar(Char::lowercaseChar)
    return if (camel == this || camel in KOTLIN_KEYWORDS) "_$camel" else camel
}

// Hard keywords only, which Kotlin essentially never extends. This list is what KotlinPoet would
// maintain for us; a miss is loud, not silent: the generated catalog would fail to compile.
private val KOTLIN_KEYWORDS = setOf(
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "import", "in",
    "interface", "is", "null", "object", "package", "return", "super", "this", "throw", "true", "try",
    "typealias", "typeof", "val", "var", "when", "while",
)
